- name: Do a bunch of setups that we need for the VMs
  hosts: all
  become: yes
  tasks:
    - name: install ntp
      yum:
        name: ntp
        update_cache: yes
        state: latest

    - name: start ntp
      service:
        name: ntpd
        state: started
        enabled: yes

    - name: disable selinux
      copy:
        src: templates/selinux
        dest: /etc/selinux/config

    - name: Ensure /etc/hosts
      template: src=templates/hosts.j2 dest=/etc/hosts

    - name: make the vagrant user
      user:
        name: vagrant
        group: users

    - name: replace /dev/random with /dev/urandom
      shell: rm -f /dev/random; ln -s /dev/urandom /dev/random


- name: Setup the master
  hosts: node1-vm
  become: yes
  tasks:
    - name: install curl
      yum:
        name: curl
        state: latest

    - name: Add CM repo
      yum_repository:
        name: clouderamanager
        description: Cloudera Manager repo
        baseurl: https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5/
        gpgkey: https://archive.cloudera.com/cm5/redhat/6/x86_64/cm/RPM-GPG-KEY-cloudera
        gpgcheck: yes


    - name: install cloudera stuff
      yum: name={{ item }} state=latest
      with_items:
        - oracle-j2sdk1.7
        - cloudera-manager-server-db-2
        - cloudera-manager-server
        - cloudera-manager-daemons

    - name: init cloudera-scm-server-db
      command: service cloudera-scm-server-db initdb

    - name: enable cloudera stuff
      service: name={{ item }} enabled=yes state=started
      with_items:
        - cloudera-scm-server-db
        - cloudera-scm-server

